language: csharp
mono:
  - 3.12.0
install:
 - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  # build linux .so
  -  ./build/make_linux_jit.sh
  # build C# solution
  - ./standalone/build_linux_x64.sh
  # test
  - mono ./testrunner/NUnit.Runners.3.0.1/tools/nunit-console.exe ./standalone/bin/slua-standalone-tests.dll
